#!/bin/sh
#
#  First try to build the lisp software.
#
echo "Building software"
scripts/make_info
if alr build
then
  echo "Build succeeded"
else
  echo "Error occured during build - Aborting"
  exit 1
fi
#
#  Next run the tests and see if there are any failures
#
echo "Running tests"
if ./lisp < test/test.lisp | grep '^...FAIL'
then
  echo "Test failures detected"
  exit 1
fi
echo "No test failures detected"
exit 0

