package BBS.lisp.info is
   --
   --  This file is auto generated by the pre-commit hook as well as
   --  the test coverage script.  It should not be edited by hand.
   --
   name           : constant String  := "Tiny Lisp";
   timestamp      : constant String  := "Tue Jul 27 13:22:45 MST 2021";
   build_date     : constant String  := "2021-Jul-27";
   version_string : constant String  := "V00.02+";
   version_date   : constant Integer := 20210727;  -- yyyymmdd
   version_number : constant Integer := 2;
end;
