package BBS.lisp.info is
   --
   --  This file is auto generated by the pre-commit hook as well as
   --  the test coverage script.  It should not be edited by hand.
   --
   name           : constant String  := "Tiny Lisp";
   timestamp      : constant String  := "Fri Aug  6 06:25:49 MST 2021";
   build_date     : constant String  := "2021-Aug-06 (master)";
   version_string : constant String  := "V00.03+";
   version_date   : constant Integer := 20210806;  -- yyyymmdd
   version_number : constant Integer := 2;
end;
